### ISSUE TITLE
Unable to find element with name 'username'

### ISSUE THREAD

**Issue by coolerUA** [get-a-clue/nodejs#2]
Using phantomjs gets error:

> $ node instagram_likebot.js 
> 
> /opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
>   goog.global.setTimeout(function() { throw exception; }, 0);
>                                       ^
> NoSuchElementError: {"errorMessage":"Unable to find element with name 'username'","request":{"headers":{"Accept":"application/json; charset=utf-8","Connection":"close","Content-Length":"35","Content-Type":"application/json;charset=UTF-8","Host":"192.168.0.19:56611"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"name\",\"value\":\"username\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/f93d0da0-ca5f-11e5-84fd-7138067e8117/element"}}
>     at new bot.Error (/opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
>     at Object.bot.response.checkResponse (/opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
>     at /opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:379:20
>     at promise.Promise.goog.defineClass.invokeCallback_ (/opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
>     at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
>     at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
>     at goog.async.run.processWorkQueue (/opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
>     at process._tickCallback (node.js:401:9)
> From: Task: WebElement.sendKeys()
>     at webdriver.WebDriver.schedule (/opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:15)
>     at webdriver.WebElement.schedule_ (/opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1817:23)
>     at webdriver.WebElement.sendKeys (/opt/insta/nodejs/instagram_likebot/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1988:17)
>     at Object.<anonymous> (/opt/insta/nodejs/instagram_likebot/instagram_likebot.js:30:42)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Function.Module.runMain (module.js:447:10)
>     at startup (node.js:139:18)

But if switch to chrome, it`s works

**Comment by get-a-clue** [comment]
Sorry, can't help you.

**Comment by coolerUA** [comment]
Кинул пул-реквест, добавляя таймаут перед поиском полей вроде как решает проблему.
